### PR TITLE
Fix multipart message formatting

### PR DESCRIPTION
**Pull request by bluesmoon**
This PR fixes a bunch of issues with multipart message formatting:
* In `get_mime_msg`, we need a \r\n between Content-Type and Content-Transfer-Encoding.
* `encode_attachment` should only encode the attachment and not add boundaries because it doesn't know how many attachments exist
* `get_body` should handle combining attachments with boundaries.
* `get_body` should add a terminating boundary at the end
* According to the RFC, all boundaries must have their own preceding `\r\n`

### CODE REVIEW

**Comment by aviks** [comment]
Thanks for this @bluesmoon. Unfortunately, there was #49 which hadn't yet been merged till just now. Would you mind rebasing and re-testing, since those changes might be relevant here.

**Comment by bluesmoon** [comment]
will do

**Comment by bluesmoon** [comment]
ok, rebased and it seems to still work.

**Comment by aviks** [comment]
This should now be in `v0.6.2`

**Pull request merged**
